name: local_storage
description: Local storage
version: 1.0.0

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  shared_preferences: ^0.5.0

dev_dependencies:
  pedantic: ^1.9.0

flutter:
  uses-material-design: true
