name: local_storage
description: Local storage
version: 1.0.0

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  path_provider: ^1.5.1
  shared_preferences: ^0.5.0
  sqflite: ^1.3.0

dev_dependencies:
  pedantic: ^1.9.0

flutter:
  uses-material-design: true
